default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: utf-8
  host: localhost

development:
  <<: *default
  database: chronagus_development

test:
  <<: *default
  database: chronagus_testing
