# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e2403aa5f76b41cb471405ce3e26d0648939efc148d9811cce1514e460828bca9732c84f25939a8b577717226fe2c62aa1c02d28d766d61f539daeb209386545

test:
  secret_key_base: 613437606a0a829deeba41e722fbd042af630952225c1f8bf6e8f788bc5d3f6d6f0651968c7c08be7e8fdebaec346126d1a587c1b94ef8e4741005956a31c0b1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
